import type { Book, Shelf, User, Department, Category, BorrowRecord, Notification, ExchangeListing } from './types';

export const departments: Department[] = [
  { id: 'cs', name: 'Computer Science', shortName: 'CS', bookCount: 14, availableCount: 9, shelfCount: 3, color: '#10B981' },
  { id: 'it', name: 'Information Technology', shortName: 'IT', bookCount: 6, availableCount: 4, shelfCount: 1, color: '#34D399' },
  { id: 'ec', name: 'Electronics', shortName: 'EC', bookCount: 5, availableCount: 3, shelfCount: 1, color: '#6EE7B7' },
  { id: 'ee', name: 'Electrical', shortName: 'EE', bookCount: 4, availableCount: 3, shelfCount: 1, color: '#059669' },
  { id: 'me', name: 'Mechanical', shortName: 'ME', bookCount: 4, availableCount: 3, shelfCount: 1, color: '#047857' },
  { id: 'ce', name: 'Civil', shortName: 'CE', bookCount: 3, availableCount: 2, shelfCount: 1, color: '#065F46' },
  { id: 'mg', name: 'Management', shortName: 'MG', bookCount: 5, availableCount: 4, shelfCount: 1, color: '#36454F' },
  { id: 'sc', name: 'Science & Humanities', shortName: 'SCI', bookCount: 9, availableCount: 6, shelfCount: 2, color: '#0B0B0B' },
];

export const categories: Category[] = [
  { id: 'fiction', name: 'Fiction', icon: 'BookOpen', bookCount: 4, color: '#10B981' },
  { id: 'nonfiction', name: 'Non-Fiction', icon: 'BookMarked', bookCount: 3, color: '#34D399' },
  { id: 'science', name: 'Science', icon: 'FlaskConical', bookCount: 5, color: '#6EE7B7' },
  { id: 'technology', name: 'Technology', icon: 'Cpu', bookCount: 6, color: '#059669' },
  { id: 'cs', name: 'Computer Science', icon: 'Code2', bookCount: 14, color: '#047857' },
  { id: 'engineering', name: 'Engineering', icon: 'Cog', bookCount: 8, color: '#065F46' },
  { id: 'math', name: 'Mathematics', icon: 'Calculator', bookCount: 3, color: '#36454F' },
  { id: 'management', name: 'Management', icon: 'Briefcase', bookCount: 5, color: '#10B981' },
  { id: 'literature', name: 'Literature', icon: 'Feather', bookCount: 3, color: '#34D399' },
  { id: 'history', name: 'History', icon: 'Landmark', bookCount: 2, color: '#6EE7B7' },
  { id: 'biography', name: 'Biography', icon: 'User', bookCount: 2, color: '#059669' },
  { id: 'psychology', name: 'Psychology', icon: 'Brain', bookCount: 2, color: '#047857' },
  { id: 'exams', name: 'Competitive Exams', icon: 'GraduationCap', bookCount: 4, color: '#065F46' },
  { id: 'reference', name: 'Reference', icon: 'Library', bookCount: 3, color: '#36454F' },
  { id: 'journals', name: 'Journals', icon: 'FileText', bookCount: 2, color: '#10B981' },
  { id: 'research', name: 'Research', icon: 'Microscope', bookCount: 3, color: '#34D399' },
];

export const shelves: Shelf[] = [
  { id: 'CS-01', name: 'CS Core Programming', floor: 1, section: 'Computer Science', department: 'Computer Science', genre: 'Computer Science', capacity: 40, bookCount: 8, availableCount: 5, qrCode: 'LV-CS-01', mapX: 52, mapY: 28, mapW: 14, mapH: 7, color: '#10B981' },
  { id: 'CS-02', name: 'CS Algorithms', floor: 1, section: 'Computer Science', department: 'Computer Science', genre: 'Computer Science', capacity: 30, bookCount: 3, availableCount: 2, qrCode: 'LV-CS-02', mapX: 68, mapY: 28, mapW: 14, mapH: 7, color: '#10B981' },
  { id: 'CS-03', name: 'CS Databases & Networks', floor: 1, section: 'Computer Science', department: 'Computer Science', genre: 'Technology', capacity: 30, bookCount: 3, availableCount: 2, qrCode: 'LV-CS-03', mapX: 52, mapY: 38, mapW: 14, mapH: 7, color: '#10B981' },
  { id: 'IT-01', name: 'IT & Software Engineering', floor: 1, section: 'Information Technology', department: 'Information Technology', genre: 'Technology', capacity: 30, bookCount: 6, availableCount: 4, qrCode: 'LV-IT-01', mapX: 68, mapY: 38, mapW: 14, mapH: 7, color: '#34D399' },
  { id: 'EC-01', name: 'Electronics & Electrical', floor: 1, section: 'Electronics', department: 'Electronics', genre: 'Engineering', capacity: 25, bookCount: 9, availableCount: 6, qrCode: 'LV-EC-01', mapX: 52, mapY: 52, mapW: 14, mapH: 7, color: '#6EE7B7' },
  { id: 'ME-01', name: 'Mechanical & Civil', floor: 1, section: 'Engineering', department: 'Mechanical', genre: 'Engineering', capacity: 25, bookCount: 7, availableCount: 5, qrCode: 'LV-ME-01', mapX: 68, mapY: 52, mapW: 14, mapH: 7, color: '#059669' },
  { id: 'SCI-01', name: 'Science & Mathematics', floor: 1, section: 'Science', department: 'Science & Humanities', genre: 'Science', capacity: 30, bookCount: 6, availableCount: 4, qrCode: 'LV-SCI-01', mapX: 52, mapY: 66, mapW: 14, mapH: 7, color: '#047857' },
  { id: 'MG-01', name: 'Management & Business', floor: 1, section: 'Management', department: 'Management', genre: 'Management', capacity: 25, bookCount: 5, availableCount: 4, qrCode: 'LV-MG-01', mapX: 68, mapY: 66, mapW: 14, mapH: 7, color: '#065F46' },
  { id: 'LIT-01', name: 'Literature & Fiction', floor: 1, section: 'Literature', department: 'Science & Humanities', genre: 'Fiction', capacity: 30, bookCount: 4, availableCount: 2, qrCode: 'LV-LIT-01', mapX: 30, mapY: 52, mapW: 14, mapH: 7, color: '#36454F' },
  { id: 'REF-01', name: 'Reference & Journals', floor: 1, section: 'Reference', department: 'Science & Humanities', genre: 'Reference', capacity: 20, bookCount: 3, availableCount: 2, qrCode: 'LV-REF-01', mapX: 30, mapY: 66, mapW: 14, mapH: 7, color: '#0B0B0B' },
];

const bookData: Omit<Book, 'id' | 'availableCopies'>[] = [
  { title: 'Clean Code', author: 'Robert C. Martin', isbn: '978-0132350884', publisher: 'Prentice Hall', year: 2008, genre: 'Computer Science', department: 'Computer Science', shelfId: 'CS-01', floor: 1, description: 'A handbook of agile software craftsmanship. Learn to write code that works, is maintainable, and reads well.', totalCopies: 5, rating: 4.8, coverColor: '#065F46', coverAccent: '#10B981', pages: 464, language: 'English' },
  { title: 'Introduction to Algorithms', author: 'Thomas H. Cormen', isbn: '978-0262033848', publisher: 'MIT Press', year: 2009, genre: 'Computer Science', department: 'Computer Science', shelfId: 'CS-02', floor: 1, description: 'A comprehensive guide to algorithms, covering a broad range of algorithms in depth.', totalCopies: 4, rating: 4.9, coverColor: '#022C22', coverAccent: '#34D399', pages: 1312, language: 'English' },
  { title: 'Python Crash Course', author: 'Eric Matthes', isbn: '978-1593279288', publisher: 'No Starch Press', year: 2019, genre: 'Computer Science', department: 'Computer Science', shelfId: 'CS-01', floor: 1, description: 'A hands-on, project-based introduction to programming using Python.', totalCopies: 6, rating: 4.7, coverColor: '#065F46', coverAccent: '#6EE7B7', pages: 544, language: 'English' },
  { title: 'Database System Concepts', author: 'Abraham Silberschatz', isbn: '978-0073523323', publisher: 'McGraw-Hill', year: 2019, genre: 'Technology', department: 'Computer Science', shelfId: 'CS-03', floor: 1, description: 'Fundamental concepts of database design and management systems.', totalCopies: 4, rating: 4.5, coverColor: '#047857', coverAccent: '#10B981', pages: 1344, language: 'English' },
  { title: 'Computer Networks', author: 'Andrew S. Tanenbaum', isbn: '978-0132126953', publisher: 'Pearson', year: 2020, genre: 'Technology', department: 'Computer Science', shelfId: 'CS-03', floor: 1, description: 'A systems approach to understanding computer networks from the physical layer up.', totalCopies: 3, rating: 4.6, coverColor: '#059669', coverAccent: '#34D399', pages: 960, language: 'English' },
  { title: 'Operating System Concepts', author: 'Abraham Silberschatz', isbn: '978-1118063330', publisher: 'Wiley', year: 2018, genre: 'Technology', department: 'Computer Science', shelfId: 'CS-03', floor: 1, description: 'The classic guide to operating system theory and practice.', totalCopies: 4, rating: 4.5, coverColor: '#064E3B', coverAccent: '#10B981', pages: 944, language: 'English' },
  { title: 'Artificial Intelligence: A Modern Approach', author: 'Stuart Russell', isbn: '978-0134610993', publisher: 'Pearson', year: 2020, genre: 'Computer Science', department: 'Computer Science', shelfId: 'CS-02', floor: 1, description: 'The most comprehensive and authoritative textbook on AI.', totalCopies: 3, rating: 4.7, coverColor: '#022C22', coverAccent: '#6EE7B7', pages: 1136, language: 'English' },
  { title: 'Machine Learning', author: 'Tom M. Mitchell', isbn: '978-0070428072', publisher: 'McGraw-Hill', year: 1997, genre: 'Computer Science', department: 'Computer Science', shelfId: 'CS-02', floor: 1, description: 'A foundational text on machine learning theory and algorithms.', totalCopies: 3, rating: 4.4, coverColor: '#065F46', coverAccent: '#34D399', pages: 432, language: 'English' },
  { title: 'Data Science from Scratch', author: 'Joel Grus', isbn: '978-1492041139', publisher: "O'Reilly", year: 2019, genre: 'Computer Science', department: 'Computer Science', shelfId: 'CS-01', floor: 1, description: 'First principles with Python for data science.', totalCopies: 4, rating: 4.3, coverColor: '#047857', coverAccent: '#10B981', pages: 406, language: 'English' },
  { title: 'Software Engineering', author: 'Ian Sommerville', isbn: '978-0133943030', publisher: 'Pearson', year: 2015, genre: 'Technology', department: 'Information Technology', shelfId: 'IT-01', floor: 1, description: 'A comprehensive introduction to software engineering principles.', totalCopies: 5, rating: 4.4, coverColor: '#059669', coverAccent: '#6EE7B7', pages: 804, language: 'English' },
  { title: 'Design Patterns', author: 'Erich Gamma', isbn: '978-0201633610', publisher: 'Addison-Wesley', year: 1994, genre: 'Technology', department: 'Information Technology', shelfId: 'IT-01', floor: 1, description: 'Elements of reusable object-oriented software design.', totalCopies: 3, rating: 4.6, coverColor: '#064E3B', coverAccent: '#34D399', pages: 395, language: 'English' },
  { title: 'The Pragmatic Programmer', author: 'David Thomas', isbn: '978-0135957059', publisher: 'Addison-Wesley', year: 2019, genre: 'Technology', department: 'Information Technology', shelfId: 'IT-01', floor: 1, description: 'Your journey to mastery in software development.', totalCopies: 4, rating: 4.8, coverColor: '#022C22', coverAccent: '#10B981', pages: 352, language: 'English' },
  { title: 'Refactoring', author: 'Martin Fowler', isbn: '978-0134757599', publisher: 'Addison-Wesley', year: 2018, genre: 'Technology', department: 'Information Technology', shelfId: 'IT-01', floor: 1, description: 'Improving the design of existing code.', totalCopies: 3, rating: 4.7, coverColor: '#065F46', coverAccent: '#6EE7B7', pages: 448, language: 'English' },
  { title: 'Code Complete', author: 'Steve McConnell', isbn: '978-0735619678', publisher: 'Microsoft Press', year: 2004, genre: 'Technology', department: 'Information Technology', shelfId: 'IT-01', floor: 1, description: 'A practical handbook of software construction.', totalCopies: 3, rating: 4.6, coverColor: '#047857', coverAccent: '#34D399', pages: 960, language: 'English' },
  { title: 'Digital Design', author: 'M. Morris Mano', isbn: '978-0132774208', publisher: 'Pearson', year: 2013, genre: 'Engineering', department: 'Electronics', shelfId: 'EC-01', floor: 1, description: 'Fundamentals of digital logic and circuit design.', totalCopies: 4, rating: 4.3, coverColor: '#059669', coverAccent: '#10B981', pages: 624, language: 'English' },
  { title: 'Microprocessor Architecture', author: 'Ramesh Gaonkar', isbn: '978-1401862157', publisher: 'Cengage', year: 2013, genre: 'Engineering', department: 'Electronics', shelfId: 'EC-01', floor: 1, description: 'Programming and applications with the 8085.', totalCopies: 3, rating: 4.2, coverColor: '#064E3B', coverAccent: '#6EE7B7', pages: 640, language: 'English' },
  { title: 'Signals and Systems', author: 'Alan V. Oppenheim', isbn: '978-0138147570', publisher: 'Pearson', year: 2013, genre: 'Engineering', department: 'Electronics', shelfId: 'EC-01', floor: 1, description: 'Analysis of continuous and discrete-time signals and systems.', totalCopies: 3, rating: 4.4, coverColor: '#022C22', coverAccent: '#10B981', pages: 952, language: 'English' },
  { title: 'Electric Circuits', author: 'Charles K. Alexander', isbn: '978-0073380575', publisher: 'McGraw-Hill', year: 2012, genre: 'Engineering', department: 'Electrical', shelfId: 'EC-01', floor: 1, description: 'Fundamentals of electric circuit analysis.', totalCopies: 4, rating: 4.3, coverColor: '#065F46', coverAccent: '#34D399', pages: 992, language: 'English' },
  { title: 'Engineering Mechanics', author: 'Russell C. Hibbeler', isbn: '978-0133918922', publisher: 'Pearson', year: 2015, genre: 'Engineering', department: 'Mechanical', shelfId: 'ME-01', floor: 1, description: 'Statics and dynamics for engineering students.', totalCopies: 4, rating: 4.4, coverColor: '#047857', coverAccent: '#10B981', pages: 720, language: 'English' },
  { title: 'Fluid Mechanics', author: 'Frank M. White', isbn: '978-0073398273', publisher: 'McGraw-Hill', year: 2015, genre: 'Engineering', department: 'Mechanical', shelfId: 'ME-01', floor: 1, description: 'Fundamentals and applications of fluid mechanics.', totalCopies: 3, rating: 4.3, coverColor: '#059669', coverAccent: '#6EE7B7', pages: 864, language: 'English' },
  { title: 'Materials Science', author: 'William D. Callister', isbn: '978-1118324578', publisher: 'Wiley', year: 2014, genre: 'Engineering', department: 'Mechanical', shelfId: 'ME-01', floor: 1, description: 'An introduction to properties and applications of materials.', totalCopies: 3, rating: 4.2, coverColor: '#064E3B', coverAccent: '#34D399', pages: 992, language: 'English' },
  { title: 'Civil Engineering Materials', author: 'Peter A. Claisse', isbn: '978-0081002759', publisher: 'Butterworth', year: 2016, genre: 'Engineering', department: 'Civil', shelfId: 'ME-01', floor: 1, description: 'Properties and applications of construction materials.', totalCopies: 2, rating: 4.0, coverColor: '#022C22', coverAccent: '#10B981', pages: 456, language: 'English' },
  { title: 'Higher Engineering Mathematics', author: 'B.S. Grewal', isbn: '978-8174092319', publisher: 'Khanna Publishers', year: 2018, genre: 'Mathematics', department: 'Science & Humanities', shelfId: 'SCI-01', floor: 1, description: 'Comprehensive coverage of engineering mathematics.', totalCopies: 5, rating: 4.5, coverColor: '#065F46', coverAccent: '#6EE7B7', pages: 1600, language: 'English' },
  { title: 'Linear Algebra Done Right', author: 'Sheldon Axler', isbn: '978-3319110790', publisher: 'Springer', year: 2015, genre: 'Mathematics', department: 'Science & Humanities', shelfId: 'SCI-01', floor: 1, description: 'A clear and concise introduction to linear algebra.', totalCopies: 3, rating: 4.6, coverColor: '#047857', coverAccent: '#10B981', pages: 340, language: 'English' },
  { title: 'University Physics', author: 'Hugh D. Young', isbn: '978-0321675420', publisher: 'Pearson', year: 2019, genre: 'Science', department: 'Science & Humanities', shelfId: 'SCI-01', floor: 1, description: 'Classical and modern physics for university students.', totalCopies: 4, rating: 4.4, coverColor: '#059669', coverAccent: '#34D399', pages: 1600, language: 'English' },
  { title: 'Organic Chemistry', author: 'Paula Y. Bruice', isbn: '978-0134042288', publisher: 'Pearson', year: 2016, genre: 'Science', department: 'Science & Humanities', shelfId: 'SCI-01', floor: 1, description: 'Structure, mechanism, and reactions of organic compounds.', totalCopies: 3, rating: 4.3, coverColor: '#064E3B', coverAccent: '#6EE7B7', pages: 1344, language: 'English' },
  { title: 'Principles of Management', author: 'Charles W.L. Hill', isbn: '978-1259546930', publisher: 'McGraw-Hill', year: 2017, genre: 'Management', department: 'Management', shelfId: 'MG-01', floor: 1, description: 'A practical approach to management principles.', totalCopies: 4, rating: 4.2, coverColor: '#022C22', coverAccent: '#10B981', pages: 720, language: 'English' },
  { title: 'Marketing Management', author: 'Philip Kotler', isbn: '978-0134496158', publisher: 'Pearson', year: 2015, genre: 'Management', department: 'Management', shelfId: 'MG-01', floor: 1, description: 'The definitive guide to marketing strategy.', totalCopies: 3, rating: 4.5, coverColor: '#065F46', coverAccent: '#34D399', pages: 832, language: 'English' },
  { title: 'Financial Accounting', author: 'Jerry J. Weygandt', isbn: '978-1118875056', publisher: 'Wiley', year: 2015, genre: 'Management', department: 'Management', shelfId: 'MG-01', floor: 1, description: 'Tools for business decision making.', totalCopies: 3, rating: 4.1, coverColor: '#047857', coverAccent: '#6EE7B7', pages: 648, language: 'English' },
  { title: 'To Kill a Mockingbird', author: 'Harper Lee', isbn: '978-0061120084', publisher: 'HarperCollins', year: 2006, genre: 'Fiction', department: 'Science & Humanities', shelfId: 'LIT-01', floor: 1, description: 'A powerful tale of racial injustice in the American South.', totalCopies: 4, rating: 4.8, coverColor: '#059669', coverAccent: '#10B981', pages: 336, language: 'English' },
  { title: '1984', author: 'George Orwell', isbn: '978-0451524935', publisher: 'Signet Classics', year: 1961, genre: 'Fiction', department: 'Science & Humanities', shelfId: 'LIT-01', floor: 1, description: 'A dystopian masterpiece about totalitarianism and surveillance.', totalCopies: 5, rating: 4.7, coverColor: '#022C22', coverAccent: '#34D399', pages: 328, language: 'English' },
  { title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', isbn: '978-0743273567', publisher: 'Scribner', year: 2004, genre: 'Fiction', department: 'Science & Humanities', shelfId: 'LIT-01', floor: 1, description: 'A classic novel of the Jazz Age and the American Dream.', totalCopies: 3, rating: 4.5, coverColor: '#064E3B', coverAccent: '#6EE7B7', pages: 180, language: 'English' },
  { title: 'Sapiens: A Brief History', author: 'Yuval Noah Harari', isbn: '978-0062316097', publisher: 'Harper', year: 2015, genre: 'History', department: 'Science & Humanities', shelfId: 'LIT-01', floor: 1, description: 'A sweeping narrative of human history from cognition to the future.', totalCopies: 4, rating: 4.7, coverColor: '#065F46', coverAccent: '#10B981', pages: 464, language: 'English' },
  { title: 'Steve Jobs', author: 'Walter Isaacson', isbn: '978-1451648539', publisher: 'Simon & Schuster', year: 2011, genre: 'Biography', department: 'Science & Humanities', shelfId: 'LIT-01', floor: 1, description: 'The authorized biography of the visionary Apple co-founder.', totalCopies: 3, rating: 4.6, coverColor: '#047857', coverAccent: '#34D399', pages: 656, language: 'English' },
  { title: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', isbn: '978-0374533557', publisher: 'FSG', year: 2013, genre: 'Psychology', department: 'Science & Humanities', shelfId: 'REF-01', floor: 1, description: 'The two systems that drive the way we think and make decisions.', totalCopies: 4, rating: 4.6, coverColor: '#059669', coverAccent: '#6EE7B7', pages: 577, language: 'English' },
  { title: 'Atomic Habits', author: 'James Clear', isbn: '978-0735211292', publisher: 'Avery', year: 2018, genre: 'Psychology', department: 'Science & Humanities', shelfId: 'REF-01', floor: 1, description: 'An easy and proven way to build good habits and break bad ones.', totalCopies: 5, rating: 4.8, coverColor: '#022C22', coverAccent: '#10B981', pages: 320, language: 'English' },
  { title: 'GATE Computer Science', author: 'GK Publications', isbn: '978-9352830155', publisher: 'GK Publications', year: 2024, genre: 'Competitive Exams', department: 'Computer Science', shelfId: 'CS-01', floor: 1, description: 'Complete preparation guide for GATE Computer Science exam.', totalCopies: 4, rating: 4.3, coverColor: '#065F46', coverAccent: '#34D399', pages: 1200, language: 'English' },
  { title: 'CAT Preparation Guide', author: 'Arun Sharma', isbn: '978-9352830148', publisher: 'McGraw-Hill', year: 2023, genre: 'Competitive Exams', department: 'Management', shelfId: 'MG-01', floor: 1, description: 'Quantitative aptitude for CAT and other MBA exams.', totalCopies: 3, rating: 4.4, coverColor: '#047857', coverAccent: '#6EE7B7', pages: 800, language: 'English' },
  { title: 'UPSC General Studies', author: 'Manohar Pandey', isbn: '978-9354834021', publisher: 'Arihant', year: 2024, genre: 'Competitive Exams', department: 'Science & Humanities', shelfId: 'REF-01', floor: 1, description: 'Comprehensive guide for UPSC Civil Services preliminary exam.', totalCopies: 3, rating: 4.2, coverColor: '#059669', coverAccent: '#10B981', pages: 900, language: 'English' },
  { title: 'GRE Verbal Reasoning', author: 'ETS', isbn: '978-1259863503', publisher: 'McGraw-Hill', year: 2023, genre: 'Competitive Exams', department: 'Science & Humanities', shelfId: 'REF-01', floor: 1, description: 'Official practice for GRE verbal reasoning section.', totalCopies: 2, rating: 4.0, coverColor: '#064E3B', coverAccent: '#34D399', pages: 400, language: 'English' },
  { title: 'Research Methodology', author: 'C.R. Kothari', isbn: '978-8122424881', publisher: 'New Age International', year: 2019, genre: 'Research', department: 'Science & Humanities', shelfId: 'REF-01', floor: 1, description: 'Methods and techniques for research in social sciences.', totalCopies: 3, rating: 4.3, coverColor: '#022C22', coverAccent: '#6EE7B7', pages: 418, language: 'English' },
  { title: 'Deep Learning', author: 'Ian Goodfellow', isbn: '978-0262035613', publisher: 'MIT Press', year: 2016, genre: 'Computer Science', department: 'Computer Science', shelfId: 'CS-02', floor: 1, description: 'The definitive textbook on deep learning, from basic to advanced.', totalCopies: 3, rating: 4.7, coverColor: '#065F46', coverAccent: '#10B981', pages: 800, language: 'English' },
  { title: 'Hands-On Machine Learning', author: 'Aurélien Géron', isbn: '978-1492032649', publisher: "O'Reilly", year: 2019, genre: 'Computer Science', department: 'Computer Science', shelfId: 'CS-02', floor: 1, description: 'Practical ML with Scikit-Learn, Keras, and TensorFlow.', totalCopies: 4, rating: 4.8, coverColor: '#047857', coverAccent: '#34D399', pages: 856, language: 'English' },
  { title: 'Python for Data Analysis', author: 'Wes McKinney', isbn: '978-1491957660', publisher: "O'Reilly", year: 2017, genre: 'Computer Science', department: 'Computer Science', shelfId: 'CS-01', floor: 1, description: 'Data wrangling with Pandas, NumPy, and IPython.', totalCopies: 4, rating: 4.5, coverColor: '#059669', coverAccent: '#6EE7B7', pages: 544, language: 'English' },
  { title: 'The Mythical Man-Month', author: 'Frederick P. Brooks', isbn: '978-0201835953', publisher: 'Addison-Wesley', year: 1995, genre: 'Technology', department: 'Information Technology', shelfId: 'IT-01', floor: 1, description: 'Essays on software engineering and project management.', totalCopies: 2, rating: 4.5, coverColor: '#064E3B', coverAccent: '#10B981', pages: 322, language: 'English' },
  { title: 'Effective Java', author: 'Joshua Bloch', isbn: '978-0134685991', publisher: 'Addison-Wesley', year: 2018, genre: 'Technology', department: 'Information Technology', shelfId: 'IT-01', floor: 1, description: 'Best practices for the Java platform.', totalCopies: 3, rating: 4.7, coverColor: '#022C22', coverAccent: '#34D399', pages: 416, language: 'English' },
  { title: 'Computer Organization', author: 'Carl Hamacher', isbn: '978-0073380650', publisher: 'McGraw-Hill', year: 2011, genre: 'Engineering', department: 'Electronics', shelfId: 'EC-01', floor: 1, description: 'Computer architecture and organization fundamentals.', totalCopies: 3, rating: 4.2, coverColor: '#065F46', coverAccent: '#6EE7B7', pages: 800, language: 'English' },
  { title: 'Thermodynamics', author: 'Yunus A. Çengel', isbn: '978-0073390174', publisher: 'McGraw-Hill', year: 2014, genre: 'Engineering', department: 'Mechanical', shelfId: 'ME-01', floor: 1, description: 'An engineering approach to thermodynamics.', totalCopies: 3, rating: 4.3, coverColor: '#047857', coverAccent: '#10B981', pages: 1008, language: 'English' },
  { title: 'Structural Analysis', author: 'R.C. Hibbeler', isbn: '978-0134610672', publisher: 'Pearson', year: 2018, genre: 'Engineering', department: 'Civil', shelfId: 'ME-01', floor: 1, description: 'Analysis of statically determinate and indeterminate structures.', totalCopies: 2, rating: 4.1, coverColor: '#059669', coverAccent: '#34D399', pages: 736, language: 'English' },
  { title: 'Discrete Mathematics', author: 'Kenneth H. Rosen', isbn: '978-0073383095', publisher: 'McGraw-Hill', year: 2018, genre: 'Mathematics', department: 'Science & Humanities', shelfId: 'SCI-01', floor: 1, description: 'Discrete structures and their applications in computer science.', totalCopies: 4, rating: 4.4, coverColor: '#064E3B', coverAccent: '#6EE7B7', pages: 1088, language: 'English' },
  { title: 'The Alchemist', author: 'Paulo Coelho', isbn: '978-0061122415', publisher: 'HarperOne', year: 2006, genre: 'Fiction', department: 'Science & Humanities', shelfId: 'LIT-01', floor: 1, description: 'A philosophical journey of a shepherd boy seeking treasure.', totalCopies: 4, rating: 4.6, coverColor: '#022C22', coverAccent: '#10B981', pages: 208, language: 'English' },
];

export const books: Book[] = bookData.map((b, i) => {
  const id = `BK-${String(i + 1).padStart(4, '0')}`;
  const borrowed = Math.floor(Math.random() * Math.min(b.totalCopies, 3));
  const available = b.totalCopies - borrowed;
  return { ...b, id, availableCopies: available };
});

export const users: User[] = [
  { id: 'U001', name: 'Aarav Sharma', email: 'aarav.s@university.edu', studentId: 'CS21B001', role: 'STUDENT', avatar: 'block-1', department: 'Computer Science', barcode: 'LIB-CS21B001', membershipType: 'Student', membershipValidTill: '2027-06-30', borrowLimit: 5, currentBorrowed: 2 },
  { id: 'U002', name: 'Priya Patel', email: 'priya.p@university.edu', studentId: 'IT22B014', role: 'STUDENT', avatar: 'block-2', department: 'Information Technology', barcode: 'LIB-IT22B014', membershipType: 'Student', membershipValidTill: '2027-06-30', borrowLimit: 5, currentBorrowed: 1 },
  { id: 'U003', name: 'Rohan Verma', email: 'rohan.v@university.edu', studentId: 'EC21B007', role: 'STUDENT', avatar: 'block-3', department: 'Electronics', barcode: 'LIB-EC21B007', membershipType: 'Student', membershipValidTill: '2027-06-30', borrowLimit: 5, currentBorrowed: 3 },
  { id: 'U004', name: 'Sneha Reddy', email: 'sneha.r@university.edu', studentId: 'ME22B021', role: 'STUDENT', avatar: 'block-4', department: 'Mechanical', barcode: 'LIB-ME22B021', membershipType: 'Student', membershipValidTill: '2027-06-30', borrowLimit: 5, currentBorrowed: 0 },
  { id: 'U005', name: 'Karthik Nair', email: 'karthik.n@university.edu', studentId: 'CE21B003', role: 'STUDENT', avatar: 'block-5', department: 'Civil', barcode: 'LIB-CE21B003', membershipType: 'Student', membershipValidTill: '2027-06-30', borrowLimit: 5, currentBorrowed: 1 },
  { id: 'U006', name: 'Ananya Iyer', email: 'ananya.i@university.edu', studentId: 'MG22B011', role: 'STUDENT', avatar: 'block-6', department: 'Management', barcode: 'LIB-MG22B011', membershipType: 'Student', membershipValidTill: '2027-06-30', borrowLimit: 5, currentBorrowed: 2 },
  { id: 'U007', name: 'Vikram Singh', email: 'vikram.s@university.edu', studentId: 'CS20B042', role: 'STUDENT', avatar: 'block-7', department: 'Computer Science', barcode: 'LIB-CS20B042', membershipType: 'Student', membershipValidTill: '2026-12-30', borrowLimit: 5, currentBorrowed: 4 },
  { id: 'U008', name: 'Divya Menon', email: 'divya.m@university.edu', studentId: 'SC22B008', role: 'STUDENT', avatar: 'block-8', department: 'Science & Humanities', barcode: 'LIB-SC22B008', membershipType: 'Student', membershipValidTill: '2027-06-30', borrowLimit: 5, currentBorrowed: 1 },
  { id: 'U009', name: 'Arjun Gupta', email: 'arjun.g@university.edu', studentId: 'EE21B019', role: 'STUDENT', avatar: 'block-9', department: 'Electrical', barcode: 'LIB-EE21B019', membershipType: 'Student', membershipValidTill: '2027-06-30', borrowLimit: 5, currentBorrowed: 2 },
  { id: 'U010', name: 'Meera Krishnan', email: 'meera.k@university.edu', studentId: 'CS23B035', role: 'STUDENT', avatar: 'block-10', department: 'Computer Science', barcode: 'LIB-CS23B035', membershipType: 'Student', membershipValidTill: '2028-06-30', borrowLimit: 5, currentBorrowed: 0 },
  { id: 'A001', name: 'Dr. Rajesh Kumar', email: 'admin@libravista.edu', studentId: 'ADMIN001', role: 'ADMIN', avatar: 'admin-1', department: 'Administration', barcode: 'LIB-ADMIN001', membershipType: 'Faculty', membershipValidTill: '2030-12-31', borrowLimit: 20, currentBorrowed: 0 },
  { id: 'A002', name: 'Prof. Lakshmi Rao', email: 'l.rao@libravista.edu', studentId: 'ADMIN002', role: 'ADMIN', avatar: 'admin-2', department: 'Administration', barcode: 'LIB-ADMIN002', membershipType: 'Faculty', membershipValidTill: '2030-12-31', borrowLimit: 20, currentBorrowed: 0 },
  { id: 'A003', name: 'Dr. Suresh Nair', email: 's.nair@libravista.edu', studentId: 'ADMIN003', role: 'ADMIN', avatar: 'admin-3', department: 'Administration', barcode: 'LIB-ADMIN003', membershipType: 'Faculty', membershipValidTill: '2030-12-31', borrowLimit: 20, currentBorrowed: 0 },
];

const today = new Date('2026-09-26');

function dateOffset(days: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

export const borrowRecords: BorrowRecord[] = [
  { id: 'BR001', bookId: 'BK-0001', bookTitle: 'Clean Code', userId: 'U001', userName: 'Aarav Sharma', borrowDate: dateOffset(-10), dueDate: dateOffset(4), returnDate: null, status: 'active' },
  { id: 'BR002', bookId: 'BK-0003', bookTitle: 'Python Crash Course', userId: 'U001', userName: 'Aarav Sharma', borrowDate: dateOffset(-5), dueDate: dateOffset(9), returnDate: null, status: 'active' },
  { id: 'BR003', bookId: 'BK-0002', bookTitle: 'Introduction to Algorithms', userId: 'U003', userName: 'Rohan Verma', borrowDate: dateOffset(-20), dueDate: dateOffset(-6), returnDate: null, status: 'overdue' },
  { id: 'BR004', bookId: 'BK-0010', bookTitle: 'Software Engineering', userId: 'U003', userName: 'Rohan Verma', borrowDate: dateOffset(-3), dueDate: dateOffset(11), returnDate: null, status: 'active' },
  { id: 'BR005', bookId: 'BK-0015', bookTitle: 'Digital Design', userId: 'U003', userName: 'Rohan Verma', borrowDate: dateOffset(-7), dueDate: dateOffset(7), returnDate: null, status: 'active' },
  { id: 'BR006', bookId: 'BK-0026', bookTitle: 'Principles of Management', userId: 'U006', userName: 'Ananya Iyer', borrowDate: dateOffset(-12), dueDate: dateOffset(2), returnDate: null, status: 'active' },
  { id: 'BR007', bookId: 'BK-0027', bookTitle: 'Marketing Management', userId: 'U006', userName: 'Ananya Iyer', borrowDate: dateOffset(-8), dueDate: dateOffset(6), returnDate: null, status: 'active' },
  { id: 'BR008', bookId: 'BK-0004', bookTitle: 'Database System Concepts', userId: 'U002', userName: 'Priya Patel', borrowDate: dateOffset(-6), dueDate: dateOffset(8), returnDate: null, status: 'active' },
  { id: 'BR009', bookId: 'BK-0005', bookTitle: 'Computer Networks', userId: 'U007', userName: 'Vikram Singh', borrowDate: dateOffset(-15), dueDate: dateOffset(-1), returnDate: null, status: 'overdue' },
  { id: 'BR010', bookId: 'BK-0006', bookTitle: 'Operating System Concepts', userId: 'U007', userName: 'Vikram Singh', borrowDate: dateOffset(-14), dueDate: dateOffset(0), returnDate: null, status: 'active' },
  { id: 'BR011', bookId: 'BK-0007', bookTitle: 'Artificial Intelligence: A Modern Approach', userId: 'U007', userName: 'Vikram Singh', borrowDate: dateOffset(-10), dueDate: dateOffset(4), returnDate: null, status: 'active' },
  { id: 'BR012', bookId: 'BK-0008', bookTitle: 'Machine Learning', userId: 'U007', userName: 'Vikram Singh', borrowDate: dateOffset(-9), dueDate: dateOffset(5), returnDate: null, status: 'active' },
  { id: 'BR013', bookId: 'BK-0029', bookTitle: 'To Kill a Mockingbird', userId: 'U005', userName: 'Karthik Nair', borrowDate: dateOffset(-4), dueDate: dateOffset(10), returnDate: null, status: 'active' },
  { id: 'BR014', bookId: 'BK-0022', bookTitle: 'Higher Engineering Mathematics', userId: 'U008', userName: 'Divya Menon', borrowDate: dateOffset(-2), dueDate: dateOffset(12), returnDate: null, status: 'active' },
  { id: 'BR015', bookId: 'BK-0018', bookTitle: 'Electric Circuits', userId: 'U009', userName: 'Arjun Gupta', borrowDate: dateOffset(-11), dueDate: dateOffset(3), returnDate: null, status: 'active' },
  { id: 'BR016', bookId: 'BK-0019', bookTitle: 'Engineering Mechanics', userId: 'U009', userName: 'Arjun Gupta', borrowDate: dateOffset(-13), dueDate: dateOffset(1), returnDate: null, status: 'active' },
  { id: 'BR017', bookId: 'BK-0001', bookTitle: 'Clean Code', userId: 'U003', userName: 'Rohan Verma', borrowDate: dateOffset(-30), dueDate: dateOffset(-16), returnDate: dateOffset(-18), status: 'returned' },
  { id: 'BR018', bookId: 'BK-0003', bookTitle: 'Python Crash Course', userId: 'U006', userName: 'Ananya Iyer', borrowDate: dateOffset(-25), dueDate: dateOffset(-11), returnDate: dateOffset(-12), status: 'returned' },
  { id: 'BR019', bookId: 'BK-0002', bookTitle: 'Introduction to Algorithms', userId: 'U001', userName: 'Aarav Sharma', borrowDate: dateOffset(-40), dueDate: dateOffset(-26), returnDate: dateOffset(-28), status: 'returned' },
  { id: 'BR020', bookId: 'BK-0010', bookTitle: 'Software Engineering', userId: 'U002', userName: 'Priya Patel', borrowDate: dateOffset(-35), dueDate: dateOffset(-21), returnDate: dateOffset(-23), status: 'returned' },
];

export const notifications: Notification[] = [
  { id: 'N001', userId: 'U001', type: 'due', title: 'Due Soon', message: 'Clean Code is due in 4 days. Return or renew before the due date.', bookId: 'BK-0001', read: false, createdAt: dateOffset(0) },
  { id: 'N002', userId: 'U001', type: 'borrow', title: 'Borrow Confirmed', message: 'You have successfully borrowed Python Crash Course. Due date: ' + dateOffset(9), bookId: 'BK-0003', read: true, createdAt: dateOffset(-5) },
  { id: 'N003', userId: 'U003', type: 'overdue', title: 'Overdue Notice', message: 'Introduction to Algorithms is 6 days overdue. Please return immediately.', bookId: 'BK-0002', read: false, createdAt: dateOffset(0) },
  { id: 'N004', userId: 'U007', type: 'overdue', title: 'Overdue Notice', message: 'Computer Networks is 1 day overdue. Please return immediately.', bookId: 'BK-0005', read: false, createdAt: dateOffset(0) },
  { id: 'N005', userId: 'U006', type: 'due', title: 'Due Soon', message: 'Principles of Management is due in 2 days.', bookId: 'BK-0026', read: false, createdAt: dateOffset(0) },
  { id: 'N006', userId: 'U001', type: 'wishlist', title: 'Wishlist Available', message: 'Good news! Deep Learning is now available for borrowing.', bookId: 'BK-0042', read: false, createdAt: dateOffset(0) },
];

export const exchangeListings: ExchangeListing[] = [
  { id: 'EX001', bookTitle: 'Head First Java', author: 'Kathy Sierra', ownerName: 'Aarav Sharma', ownerDepartment: 'Computer Science', condition: 'Good', status: 'available', coverColor: '#065F46', description: 'Great for learning Java fundamentals. Some highlights in first 3 chapters.' },
  { id: 'EX002', bookTitle: 'The Selfish Gene', author: 'Richard Dawkins', ownerName: 'Divya Menon', ownerDepartment: 'Science & Humanities', condition: 'Like New', status: 'available', coverColor: '#047857', description: 'Barely used. Excellent condition.' },
  { id: 'EX003', bookTitle: 'Cracking the Coding Interview', author: 'Gayle McDowell', ownerName: 'Vikram Singh', ownerDepartment: 'Computer Science', condition: 'Good', status: 'requested', coverColor: '#022C22', description: '189 programming questions and solutions. Well-used but complete.' },
  { id: 'EX004', bookTitle: 'Rich Dad Poor Dad', author: 'Robert Kiyosaki', ownerName: 'Ananya Iyer', ownerDepartment: 'Management', condition: 'Fair', status: 'available', coverColor: '#059669', description: 'Some wear on cover. Pages are clean.' },
  { id: 'EX005', bookTitle: 'The Power of Habit', author: 'Charles Duhigg', ownerName: 'Meera Krishnan', ownerDepartment: 'Computer Science', condition: 'Like New', status: 'available', coverColor: '#064E3B', description: 'Read once. Pristine condition.' },
  { id: 'EX006', bookTitle: 'Structures: Or Why Things Don\'t Fall Down', author: 'J.E. Gordon', ownerName: 'Karthik Nair', ownerDepartment: 'Civil', condition: 'Good', status: 'available', coverColor: '#36454F', description: 'Fascinating intro to structural engineering.' },
  { id: 'EX007', bookTitle: 'Surely You\'re Joking, Mr. Feynman!', author: 'Richard Feynman', ownerName: 'Rohan Verma', ownerDepartment: 'Electronics', condition: 'Like New', status: 'requested', coverColor: '#022C22', description: 'Adventures of a curious character. Excellent condition.' },
];

export function getBookAvailability(book: Book): 'available' | 'few' | 'borrowed' | 'reserved' {
  if (book.availableCopies === 0) return 'borrowed';
  if (book.availableCopies === 1) return 'few';
  return 'available';
}

export function getAvailabilityBadge(av: 'available' | 'few' | 'borrowed' | 'reserved') {
  switch (av) {
    case 'available': return { label: 'Available', class: 'badge-green', color: '#10B981' };
    case 'few': return { label: 'Few Copies', class: 'badge-orange', color: '#F59E0B' };
    case 'borrowed': return { label: 'Borrowed', class: 'badge-red', color: '#EF4444' };
    case 'reserved': return { label: 'Reserved', class: 'badge-blue', color: '#0EA5E9' };
  }
}
